first: "test first value"
name: "test name value"
number: 6
nested:
  test: "nested test value"
list-value:
  - 1
  - 2
  - 3
item:
  material: STONE
  amount: 1
  name: "Test"
items:
  1:
    material: "BLACK_STAINED_GLASS_PANE"
    name: " "
